name: Continuous Integration Carlos

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pruebas de SAST
        run: echo "Ejecución de pruebas de SAST"

      - name: Crear archivo credentials.ini
        run: |
          echo "[DEFAULT]" > credentials.ini
          echo "username=${{ secrets.USERNAME }}" >> credentials.ini
          echo "password=${{ secrets.PASSWORD }}" >> credentials.ini

      - name: Verificar archivo generado
        run: cat credentials.ini

      - name: Build docker image
        run: |
          docker build -t devops_ws:latest -t devops_ws:$(date +%s) .

      - name: Subir credentials.ini como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: credentials-ini
          path: credentials.ini
